version: '2'

services:
 app:
  image: m3adow/seafile
  restart: always
  ports:
  - 8000:8000
  - 8082:8082
  environment:
      - SEAFILE_NAME=seafilebox
      - SEAFILE_ADDRESS=<ip here>
      - SEAFILE_ADMIN=<email adddy here>
      - SEAFILE_ADMIN_PW=<passwd here>

  volumes:
    - /home/aglass/seafileserver/seafile:/seafile

 apache:
   image: eboraas/apache
   container_name: apache
   restart: always
   depends_on:
     - app
   links:
    - app
#   ports:
#     - 8000:8000
#     - 8082:8082
