version: '2'

services:
 app:
  image: m3adow/seafile
  restart: always
  ports:
  - 8000:8000
  - 8082:8082
  environment:
      - SEAFILE_NAME=seafilebox
      - SEAFILE_ADDRESS=127.0.0.1
      - SEAFILE_ADMIN=admin
      - SEAFILE_ADMIN_PW=admin

  volumes:
    - ./store:/seafile

 nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./store/nginx.conf:/etc/nginx/nginx.conf:ro

